## Menu resource

### getting all menus

GET http://localhost:3000/api/menus

### getting menus based on a menu id

GET http://localhost:3000/api/menus/2


### getting menus based on a category

GET http://localhost:3000/api/menus/category/lunch

### getting special menus

GET http://localhost:3000/api/menus/specials/true


### getting all users

GET http://localhost:3000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX2xldmVsX2lkIjoxLCJpYXQiOjE3MzM3NDAxNjIsImV4cCI6MTczMzgyNjU2Mn0.4WVuUtIlcRWfzp3YqPRqUPa5Ish-BiyysmVHQdy0UtE



### getting all orders 

GET http://localhost:3000/api/orders

### getting all orders based on a customer name

GET http://localhost:3000/api/orders/customer/Elli%20Riskala

### getting all orders based on user id

GET http://localhost:3000/api/orders/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MzM2Njc4MTUsImV4cCI6MTczMzc1NDIxNX0.yfaJ_w-n8IKUepJgyIXODCeJrJ30LyF-fRYVeOj1b_E

### getting all orders based on order status

GET http://localhost:3000/api/orders/status/Inprogress

### getting all orders based on a order id

GET http://localhost:3000/api/orders/11
Content-Type: application/json

### create an order

POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "customer_name": "Elli Riskala",
    "order_items": [
        {
            "menu_id": 2,
            "course_name": "Ocean Roll",
            "item_quantity": 1,
            "comment": "extra wasabi"
        }
    ],
    "total_price": 10,
    "order_status": "pending",
    "order_type": "pickup"
}

### update an order

PUT http://localhost:3000/api/orders/10
Content-Type: application/json

{
    "order_status": "Inprogress"
}

### get user by id

GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX2xldmVsX2lkIjoxLCJpYXQiOjE3MzM2ODI0NzIsImV4cCI6MTczMzc2ODg3Mn0.AUz8g_55HjXE-GJwabfsMiMiqVHyv-EL8BaqUAYWwVA


### get reservation by id

GET http://localhost:3000/api/reservations/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3MzMyMDk2NzAsImV4cCI6MTczMzI5NjA3MH0.uSLnivGufTNRDFpLi2rONKd-bqXatTKGAhiZelxbQj4

### log in 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "ellinoora@metropolia.fi",
  "password": "Ellinoora01"
}