## Menu resource

### getting all menus

GET http://localhost:3000/api/menus

### getting menus based on a menu id

GET http://localhost:3000/api/menus/2


### getting menus based on a category

GET http://localhost:3000/api/menus/category/lunch

### getting special menus

GET http://localhost:3000/api/menus/specials/true


### getting all users

GET http://localhost:3000/api/users

### getting all orders 

GET http://localhost:3000/api/orders

### getting all orders based on a customer name

GET http://localhost:3000/api/orders/customer/Elli%20Riskala

### getting all orders based on user id

GET http://localhost:3000/api/orders/user/2

### getting all orders based on order status

GET http://localhost:3000/api/orders/status/Inprogress

### getting all orders based on a order id

GET http://localhost:3000/api/orders/4


### create an order

POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "customer_name": "Elli Riskala",
    "order_items": [
        {
            "menu_id": 2,
            "course_name": "Ocean Roll",
            "item_quantity": 1,
            "comment": "extra wasabi"
        }
    ],
    "total_price": 10,
    "order_status": "pending",
    "order_type": "pickup"
}

### update an order

PUT http://localhost:3000/api/orders/1
Content-Type: application/json

{
    "order_status": "Inprogress"
}

### get user by id

GET http://localhost:3000/api/users/2