## Menu resource

### getting all menus

GET http://localhost:3000/api/menus


### getting menus based on a category

GET http://localhost:3000/api/menus/lunch

### getting special menus

GET http://localhost:3000/api/menus/is_special


### getting all users

GET http://localhost:3000/api/users

### getting all orders 

GET http://localhost:3000/api/orders

### getting all orders based on order status

GET http://localhost:3000/api/orders/Inprogress

### getting all orders based on a order id

GET http://localhost:3000/api/orders/10

### getting all orders based on a user id

GET http://localhost:3000/api/orders/user/1

### create an order

POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "customer_name": "Elli Riskala",
    "order_items": [
        {
            "menu_id": 1,
            "course_name": "Kyoto Bliss",
            "item_quantity": 2,
            "comment": "extra wasabi"
        }
    ],
    "total_price": 20,
    "order_status": "pending",
    "order_type": "delivery"
}

### update an order

PUT http://localhost:3000/api/orders/1
Content-Type: application/json

{
    "order_status": "Inprogress"
}

